# Generated by Django 3.0 on 2019-12-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asesor', '0001_initial'),
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='asesore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorexterno_del_alumno', to='asesor.AsesorExterno'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asesori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorinterno_del_alumno', to='asesor.AsesorInterno'),
        ),
    ]
