# Generated by Django 2.0.5 on 2019-10-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20191010_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='matricula',
            new_name='NoControl',
        ),
    ]
