# Generated by Django 2.2 on 2019-12-15 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superusuario', '0001_initial'),
        ('alumno', '0003_auto_20191205_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_del_proyecto', to='superusuario.Carrera'),
        ),
    ]
