# Generated by Django 2.0.5 on 2019-10-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0001_initial'),
        ('superusuario', '0002_empresa_institucion_periodo'),
        ('alumno', '0003_auto_20191014_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='asesore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorexterno_del_alumno', to='asesor.AsesorExterno'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='asesori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorinterno_del_alumno', to='asesor.AsesorInterno'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_del_alumno', to='superusuario.Empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion_del_alumno', to='superusuario.Institucion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodo_del_alumno', to='superusuario.Periodo'),
        ),
    ]
