# Generated by Django 2.2 on 2020-02-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0002_auto_20191205_0928'),
        ('alumno', '0005_proyecto_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_evaluacion', models.IntegerField(default=1)),
                ('calificacion_interna', models.IntegerField(default=0)),
                ('calificacion_externa', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno_evaluado', to='alumno.Alumno')),
                ('asesore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorexterno_evalua', to='asesor.AsesorExterno')),
                ('asesori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesorinterno_evalua', to='asesor.AsesorInterno')),
            ],
        ),
    ]
