# Generated by Django 3.0 on 2019-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_admin', 'Is_Admin'),),
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.ImageField(default='default.jpeg', null=True, upload_to='flyers')),
                ('titulo', models.CharField(default='Oferta de Trabajo', max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('telefono_contacto', models.CharField(max_length=10, null=True)),
                ('correo_contacto', models.CharField(max_length=100, null=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
