# Generated by Django 2.2 on 2019-12-12 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinador', '0002_coordinador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='creado_por',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
