# Generated by Django 2.2 on 2019-11-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_auto_20191121_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='carrera',
        ),
    ]
