# Generated by Django 2.2 on 2019-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_remove_coordinador_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer', models.ImageField(default='default.jpeg', null=True, upload_to='flyers')),
                ('titulo', models.CharField(default='Oferta de Trabajo', max_length=50)),
                ('descripcion', models.TextField(null=True)),
                ('telefono_contacto', models.CharField(max_length=10, null=True)),
                ('correo_contacto', models.CharField(max_length=100, null=True)),
                ('vigente', models.BooleanField()),
            ],
        ),
    ]
