# Generated by Django 3.0 on 2019-12-14 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinador', '0003_auto_20191212_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publico_oferta', to=settings.AUTH_USER_MODEL),
        ),
    ]
