# Generated by Django 2.2.6 on 2019-12-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superusuario', '0001_initial'),
        ('coordinador', '0004_auto_20191214_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera_oferta', to='superusuario.Carrera'),
        ),
    ]
