# Generated by Django 2.2 on 2019-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superusuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='logo',
            field=models.ImageField(default='default.png', null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
